const router = require('express').Router();
const truckRoutes = require('./weather');
const yelpRoutes = require('./pwnd');
const favoriteRoutes = require('./calculator');
const userRoutes = require('./users');
router.use('/trucks', truckRoutes);
router.use('/yelpreviews', yelpRoutes);
router.use('/favorites', favoriteRoutes);
router.use('/users', userRoutes);
module.exports = router;